services:
  - type: web
    name: bajaj-automation
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
